language: erlang # wither art thou, Go?

install:
 - hg clone -r weekly https://code.google.com/p/go $HOME/go
 - cd $HOME/go/src && ./make.bash
 - mkdir -p $HOME/src || true
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - ln -s $HOME/builds/mattn/go-uwsgi $HOME/src/go-uwsgi
 - go get -v github.com/mattn/go-uwsgi

script:
 - cd $HOME/src/go-uwsgi && go build -v .
 - cd $HOME/src/go-uwsgi && go test -v .
